services:
    # always have shade-agent-api first in order of services
    shade-agent-api:
        environment:
            NEAR_ACCOUNT_ID: ${NEAR_ACCOUNT_ID}
            NEAR_SEED_PHRASE: ${NEAR_SEED_PHRASE}
            API_CODEHASH: ${API_CODEHASH}
            APP_CODEHASH: ${APP_CODEHASH}
            ENTROPY: ${ENTROPY}
            NEXT_PUBLIC_contractId: ${NEXT_PUBLIC_contractId}
            SHADE_AGENT_PORT: ${SHADE_AGENT_PORT}
        platform: linux/amd64 # Explicitly set for TDX
        # shade-agent-api-image
        image: mattdlockyer/shade-agent-api@sha256:3858c9828e510671d1bc0975d3853087b0aa859260e4c1c7e8b068e57bc0fe70
        container_name: shade-agent-api
        ports:
            - '3140:3140'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
    shade-agent-api-test:
        platform: linux/amd64 # Explicitly set for TDX
        # shade-agent-app-image
        image: mattdlockyer/shade-agent-api-test@sha256:76ed019fba9c9c946f292fad1b944d39e31ce54d969d19f47b16606cbf1af9a5
        container_name: shade-agent-api-test
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
