services:
    # always have shade-agent-api first in order of services
    shade-agent-api:
        environment:
            NEAR_ACCOUNT_ID: ${NEAR_ACCOUNT_ID}
            NEAR_SEED_PHRASE: ${NEAR_SEED_PHRASE}
            API_CODEHASH: ${API_CODEHASH}
            APP_CODEHASH: ${APP_CODEHASH}
            ENTROPY: ${ENTROPY}
            NEXT_PUBLIC_contractId: ${NEXT_PUBLIC_contractId}
            SHADE_AGENT_PORT: ${SHADE_AGENT_PORT}
        platform: linux/amd64 # Explicitly set for TDX
        # shade-agent-api-image
        image: mattdlockyer/shade-agent-api@sha256:202ed776d83c4aabc5aae6a8a2efa4900fde4864e8c1cde6944780d6c716b364
        container_name: shade-agent-api
        ports:
            - '3140:3140'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
    shade-agent-api-test:
        platform: linux/amd64 # Explicitly set for TDX
        # shade-agent-app-image
        image: mattdlockyer/shade-agent-api-test@sha256:048fcbd4cf488b9d6df4e11ec12e91d5da1d1a2e41c1afce2223f8f4170575b8
        container_name: shade-agent-api-test
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
